### PR TITLE
Update Bitcoins.java

### PR DESCRIPTION
**Pull request by Hibero**
Spent some time trying to understand the code. I changed all the relevant code. I did not see any thing that would make any reference errors while changing them.

### CODE REVIEW

**Comment by mark-bl** [comment]
If you look at this issue ( which you've opened )
https://github.com/FuzzyBearBTC/android-peercoinwallet/issues/13

the main developer of mycelium might help with the code , I think we should wait and see what happens before we change the code too much.

If he will add Peercoin support to the official client we won't have play catch up with the official client.
Which will result in a faster development cycle and combined  resources. 

Mark.

**Comment by Hibero** [comment]
I see the possible advantage of waiting but I see no reason not to reduce the amount of work for the dev (if he does come in). It also allowed me to notice that there is a considerable amount of dependencies on the java version of Bitcoin. If that is the case we may need to focus on a java version of peercoin before working on this wallet.

**Comment by mark-bl** [comment]
Yea I've looked also into the code ( made a few changes ).
The big issue I see is that @apetersson said he has plans, which means that we might change the code in a way that will be counter productive from his point of view.

@FuzzyBearBTC have you spoken with him ?

**Comment by FuzzyBearBTC** [comment]
@mark-bl @Hibero we have added each other on skype and are trying to catch each other at a good time, hopefully will speak today at some point and see what the best plan of action is.  I will merge this request as I see we may as well make some progress and these changes can be passed over in a commit to him if he wants to work on his own repo, or we can merge at later date.  Its nice to see such activity on the repo and I am happy to reward the tips for this good work

**Pull request merged**
